version: 2
jobs:
  build:
    working_directory: ~/workspace
    branches:
      only:
        - develop
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - setup_remote_docker

      # Install dependencies
      - run:
          name: docker version
          command: docker --version

      # Install dependencies
      - run:
          name: bundle install
          command: bundle install

      - run:
          name: which rspec
          command: which rspec

      # Upload document
      - run:
          name: run test
          command: ./run-tests.sh

      # Deploy
      - run:
          name: deploy docker images
          command: ./deploy.sh
