version: '2'
services:
  web:
    build: .
    image: slowhand/rails:1.0
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
